
[workspace]
resolver = "3"
members = ["macros", "parsing","render-engine"]

[workspace.dependencies]
foldhash = "0.1.5" # Can't be updated for compatibility with vulkano
macros = { path = "./macros/" }
shaderc = { version = "0.10", features = ["build-from-source"] }
sdl3 = { version = "0.20", features = ["raw-window-handle", "build-from-source"] }
syn = { version = "3" }
parsing = { path = "./parsing/" }
proc-macro2 = "1.0.107"
quote = "1.0.47"
uuid = { version = "1.26", features = ["v7"] }
vulkano = "0.35.0"
